export const environments = {
    codeLength : 9,
    URL : "http://localhost:3000",
    initialTab : "finder-tab",
    codeError: "Parking spot not found",
    footer: "© Powered by Elfak",
    labelEnterCodeString:"Enter your code here:",
    labelTimeString:"Duration: ",
    labelPriceString:"Price: ",
    labelRemainingTimeString: "Remaining time until penalty kicks in: ",
    labelRemainingTimePenaltyString: "You have exceeded the time limit.",
    pricePerSecond: 0.2,
    currency: "RSD",
    paymentInfo: "Parking time ended, your vehicle is on the way. Thank you for using our services.\nEstimated price: ",
    findParkingInfoString: "Please select your location to find nearby parking.",
};