export const environments = {
    codeLength : 9,
    URL : "http://localhost:3000",
    initialTab : "finder-tab",
    codeError: "Parking spot not found",
    footer: "© Powered by Elfak",
    labelEnterCodeString:"Enter your code here:",
    labelTimeString:"Duration: ",
    labelPriceString:"Price: ",
    labelRemainingTimeString: "Remaining time until penalty kicks in: ",
    labelRemainingTimePenaltyString: "You have exceeded the time limit.",
    pricePerSecond: 0.2,
    currency: "RSD",
    paymentInfo: "Parking time ended, your vehicle is on the way. Thank you for using our services.\nEstimated price: ",
    findParkingInfoString: "Please select your location to find nearby parking.",
    mapLink: "https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css",
    mapToken: "pk.eyJ1IjoiYW5kMXJpamEiLCJhIjoiY2w2bmxxNnA5MDIyazNpbXR2MTE5ZG0zbCJ9.TSyRXbo87WwCHPRC0EmVag",
    offsets: [0.001, 0.002, 0.003, 0.004, 0.005, 0.01],
    waitTime: 1000,
    checkCodeDelay: 500,
    secondsInHour: 360,
    secondsInMinutes: 60,
    roundFactor: 100,
};